"""baseline_flow_and_adk_schemas

Revision ID: 042e6ac5de67
Revises: 
Create Date: 2026-09-06 15:53:02.127931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '042e6ac5de67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS flow")
    op.execute("CREATE SCHEMA IF NOT EXISTS adk")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('new', 'intake', 'profile_ready', 'dormant', 'blocked', name='lifecycle_status_enum', schema='flow'), server_default='new', nullable=False),
    sa.Column('consent_status', sa.Enum('pending', 'granted', 'declined', 'withdrawn', name='consent_status_enum', schema='flow'), server_default='pending', nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_message_id', sa.String(length=255), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_candidates_phone_number'), 'candidates', ['phone_number'], unique=True, schema='flow')
    op.create_table('candidate_location_prefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('location_raw', sa.String(length=255), nullable=False),
    sa.Column('location_norm', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=20), server_default='preferred', nullable=False),
    sa.Column('work_mode', sa.String(length=50), nullable=True),
    sa.Column('is_hard_requirement', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_candidate_location_prefs_candidate_id'), 'candidate_location_prefs', ['candidate_id'], unique=False, schema='flow')
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('current_ctc_annual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_ctc_annual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=True),
    sa.Column('education_level', sa.String(length=255), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id'),
    schema='flow'
    )
    op.create_table('candidate_role_prefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('role_raw', sa.String(length=255), nullable=False),
    sa.Column('role_norm', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('strength', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_candidate_role_prefs_candidate_id'), 'candidate_role_prefs', ['candidate_id'], unique=False, schema='flow')
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_raw', sa.String(length=255), nullable=False),
    sa.Column('skill_norm', sa.String(length=255), nullable=False),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='current', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_norm', name='uq_candidate_skill_norm'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False, schema='flow')
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'simulator', name='channel_enum', schema='flow'), server_default='simulator', nullable=False),
    sa.Column('adk_session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'awaiting_reply', 'closed', 'disengaged', 'escalated', 'blocked', name='conversation_status_enum', schema='flow'), server_default='active', nullable=False),
    sa.Column('mode', sa.Enum('consent', 'intake', 'refresh', name='conversation_mode_enum', schema='flow'), server_default='consent', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deflection_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('abuse_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_conversations_candidate_id'), 'conversations', ['candidate_id'], unique=False, schema='flow')
    op.create_table('candidate_attributes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('candidate_stated', 'candidate_confirmed', 'resume', 'llm_inferred', 'system_calculated', 'recruiter_verified', 'channel_metadata', name='source_enum', schema='flow'), nullable=False),
    sa.Column('confidence', sa.Enum('confirmed', 'ambiguous', 'inferred', 'unknown', name='confidence_enum', schema='flow'), nullable=False),
    sa.Column('status', sa.Enum('current', 'superseded', 'stale', 'conflicted', 'rejected', name='attribute_status_enum', schema='flow'), server_default='current', nullable=False),
    sa.Column('data_class', sa.Enum('operational', 'personal', 'protected', name='data_class_enum', schema='flow'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['flow.conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['flow.candidate_attributes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index('ix_candidate_attributes_candidate_class', 'candidate_attributes', ['candidate_id', 'data_class'], unique=False, schema='flow')
    op.create_index('ix_candidate_attributes_candidate_status', 'candidate_attributes', ['candidate_id', 'status'], unique=False, schema='flow')
    op.create_index('ix_candidate_attributes_current', 'candidate_attributes', ['candidate_id', 'key'], unique=True, schema='flow', postgresql_where="status = 'current'")
    op.create_index(op.f('ix_flow_candidate_attributes_candidate_id'), 'candidate_attributes', ['candidate_id'], unique=False, schema='flow')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='direction_enum', schema='flow'), nullable=False),
    sa.Column('channel_message_id', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_ref', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['flow.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_message_id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_messages_candidate_id'), 'messages', ['candidate_id'], unique=False, schema='flow')
    op.create_index(op.f('ix_flow_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='flow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_messages_conversation_id'), table_name='messages', schema='flow')
    op.drop_index(op.f('ix_flow_messages_candidate_id'), table_name='messages', schema='flow')
    op.drop_table('messages', schema='flow')
    op.drop_index(op.f('ix_flow_candidate_attributes_candidate_id'), table_name='candidate_attributes', schema='flow')
    op.drop_index('ix_candidate_attributes_current', table_name='candidate_attributes', schema='flow', postgresql_where="status = 'current'")
    op.drop_index('ix_candidate_attributes_candidate_status', table_name='candidate_attributes', schema='flow')
    op.drop_index('ix_candidate_attributes_candidate_class', table_name='candidate_attributes', schema='flow')
    op.drop_table('candidate_attributes', schema='flow')
    op.drop_index(op.f('ix_flow_conversations_candidate_id'), table_name='conversations', schema='flow')
    op.drop_table('conversations', schema='flow')
    op.drop_index(op.f('ix_flow_candidate_skills_candidate_id'), table_name='candidate_skills', schema='flow')
    op.drop_table('candidate_skills', schema='flow')
    op.drop_index(op.f('ix_flow_candidate_role_prefs_candidate_id'), table_name='candidate_role_prefs', schema='flow')
    op.drop_table('candidate_role_prefs', schema='flow')
    op.drop_table('candidate_profiles', schema='flow')
    op.drop_index(op.f('ix_flow_candidate_location_prefs_candidate_id'), table_name='candidate_location_prefs', schema='flow')
    op.drop_table('candidate_location_prefs', schema='flow')
    op.drop_index(op.f('ix_flow_candidates_phone_number'), table_name='candidates', schema='flow')
    op.drop_table('candidates', schema='flow')

    op.execute("DROP TYPE IF EXISTS flow.lifecycle_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.consent_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.channel_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.conversation_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.conversation_mode_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.source_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.confidence_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.attribute_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.data_class_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS flow.direction_enum CASCADE")

    op.execute("DROP SCHEMA IF EXISTS adk CASCADE")
    # ### end Alembic commands ###
