"""add recruiters, recruiter_notes, and candidate assignment

Revision ID: 6253ae847a58
Revises: 668bda89b6be
Create Date: 2026-09-07 00:31:23.343241

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6253ae847a58'
down_revision: str | Sequence[str] | None = '668bda89b6be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('recruiter', 'admin', name='recruiter_role_enum', schema='flow'), server_default='recruiter', nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_recruiters_api_key_hash'), 'recruiters', ['api_key_hash'], unique=True, schema='flow')
    op.create_index(op.f('ix_flow_recruiters_email'), 'recruiters', ['email'], unique=True, schema='flow')
    op.create_table('recruiter_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['flow.recruiters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_recruiter_notes_candidate_id'), 'recruiter_notes', ['candidate_id'], unique=False, schema='flow')
    op.create_index(op.f('ix_flow_recruiter_notes_recruiter_id'), 'recruiter_notes', ['recruiter_id'], unique=False, schema='flow')
    op.add_column('candidates', sa.Column('assigned_recruiter_id', sa.UUID(), nullable=True), schema='flow')
    op.create_index(op.f('ix_flow_candidates_assigned_recruiter_id'), 'candidates', ['assigned_recruiter_id'], unique=False, schema='flow')
    op.create_foreign_key(
        'fk_candidates_assigned_recruiter_id_recruiters',
        'candidates', 'recruiters', ['assigned_recruiter_id'], ['id'],
        source_schema='flow', referent_schema='flow', ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_candidates_assigned_recruiter_id_recruiters',
        'candidates', schema='flow', type_='foreignkey',
    )
    op.drop_index(op.f('ix_flow_candidates_assigned_recruiter_id'), table_name='candidates', schema='flow')
    op.drop_column('candidates', 'assigned_recruiter_id', schema='flow')
    op.drop_index(op.f('ix_flow_recruiter_notes_recruiter_id'), table_name='recruiter_notes', schema='flow')
    op.drop_index(op.f('ix_flow_recruiter_notes_candidate_id'), table_name='recruiter_notes', schema='flow')
    op.drop_table('recruiter_notes', schema='flow')
    op.drop_index(op.f('ix_flow_recruiters_email'), table_name='recruiters', schema='flow')
    op.drop_index(op.f('ix_flow_recruiters_api_key_hash'), table_name='recruiters', schema='flow')
    op.drop_table('recruiters', schema='flow')
    # ### end Alembic commands ###
    # Enum types are not dropped by drop_table — matches the project
    # convention in 042e6ac5de67 (baseline). Without this, a re-upgrade
    # after downgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS flow.recruiter_role_enum CASCADE")
