"""initial flow schema

Revision ID: 9c496e6d1101
Revises: 
Create Date: 2026-09-06 12:13:16.245796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c496e6d1101'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_phone_number'), 'candidates', ['phone_number'], unique=True)
    op.create_table('candidate_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_locations_candidate_id'), 'candidate_locations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_locations_location'), 'candidate_locations', ['location'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('current_ctc', sa.Float(), nullable=True),
    sa.Column('expected_ctc', sa.Float(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('candidate_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_roles_candidate_id'), 'candidate_roles', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_roles_role'), 'candidate_roles', ['role'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_skill'), 'candidate_skills', ['skill'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_candidate_id'), 'conversations', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_candidate_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_candidate_skills_skill'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_candidate_roles_role'), table_name='candidate_roles')
    op.drop_index(op.f('ix_candidate_roles_candidate_id'), table_name='candidate_roles')
    op.drop_table('candidate_roles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_candidate_locations_location'), table_name='candidate_locations')
    op.drop_index(op.f('ix_candidate_locations_candidate_id'), table_name='candidate_locations')
    op.drop_table('candidate_locations')
    op.drop_index(op.f('ix_candidates_phone_number'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
