"""add rate_limit_hits table

Revision ID: d97b909d1738
Revises: 42c70b2325f7
Create Date: 2026-09-07 01:41:34.100261

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd97b909d1738'
down_revision: str | Sequence[str] | None = '42c70b2325f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index('ix_flow_rate_limit_key_created_at', 'rate_limit_hits', ['key', 'created_at'], unique=False, schema='flow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_rate_limit_key_created_at', table_name='rate_limit_hits', schema='flow')
    op.drop_table('rate_limit_hits', schema='flow')
    # ### end Alembic commands ###
