"""create_moderation_events_table

Revision ID: f6b9affc97e7
Revises: 042e6ac5de67
Create Date: 2026-09-06 16:59:14.136837

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6b9affc97e7'
down_revision: str | Sequence[str] | None = '042e6ac5de67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['flow.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['flow.conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['flow.messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='flow'
    )
    op.create_index(op.f('ix_flow_moderation_events_candidate_id'), 'moderation_events', ['candidate_id'], unique=False, schema='flow')
    op.create_index(op.f('ix_flow_moderation_events_conversation_id'), 'moderation_events', ['conversation_id'], unique=False, schema='flow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_moderation_events_conversation_id'), table_name='moderation_events', schema='flow')
    op.drop_index(op.f('ix_flow_moderation_events_candidate_id'), table_name='moderation_events', schema='flow')
    op.drop_table('moderation_events', schema='flow')
    # ### end Alembic commands ###
